[env]
RUSTFLAGS = "--cfg=web_sys_unstable_apis"
[config]
default_to_workspace = false

# [tasks.init]
# command = "mkdir"
# args = ["-p", "dist/en/"]
#
# [tasks.doc-en]
# command = "cargo"
# args = ["run", "--bin", "gen", "--", "-i", "en", "-o", "app/docs/en"]

[tasks.dev]
#dependencies = ["init", "doc-en"]
command = "trunk"
args = ["--config", "Trunk.toml", "serve", "--open"]

[tasks.build]
#dependencies = ["init", "doc-en"]
command = "trunk"
args = ["--config", "Trunk.toml", "build", "--release"]
