[env]
RUSTFLAGS = "--cfg=web_sys_unstable_apis"
[config]
default_to_workspace = false

[tasks.init]
command = "mkdir"
args = ["-p", "dist/en/", "dist/es/", "dist/zh-CN/"]

[tasks.doc-en]
command = "cargo"
args = ["run", "--bin", "gen", "--", "-i", "en", "-o", "app/docs/en"]

[tasks.doc-es]
command = "cargo"
args = ["run", "--bin", "gen", "--", "-i", "es", "-o", "app/docs/es"]

[tasks.doc-zh-CN]
command = "cargo"
args = ["run", "--bin", "gen", "--", "-i", "zh-CN", "-o", "app/docs/zh-CN"]

[tasks.dev]
dependencies = ["init", "doc-en", "doc-es", "doc-zh-CN"]
command = "trunk"
args = ["--config", "Trunk.toml", "serve", "--features", "github", "--open"]

[tasks.build]
dependencies = ["init", "doc-en", "doc-es", "doc-zh-CN"]
command = "trunk"
args = ["--config", "Trunk.toml", "build", "--features", "github", "--release"]
