[[hooks]]
stage = "pre_build"
command = "sh"
#command_arguments = ["-c", "bun x @unocss/cli src/**/*.rs index.html --out-file style/output.css"]
command_arguments = ["-c", "npx @unocss/cli src/**/*.rs index.html --out-file style/output.css"]
