[build]
target = "app/index.html"
dist = "dist"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "app/node_modules/.bin/unocss",
  "-c",
  "app/uno.config.ts",
  "app/src/**/*.rs",
  "-o",
  "app/style/output.css",
]

[watch]
watch = ["app/index.scss", "app/src"]

[tools]
wasm_bindgen = "0.2.90"

[serve]
address = "0.0.0.0"
