[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "post_build"
command = "node"
command_arguments = [
  "node_modules/.bin/unocss",
  "-c",
  "uno.config.ts",
  "src/**/*.rs",
  "-o",
  "style/output.css",
]

[watch]
watch = ["index.scss", "src"]

[tools]
wasm_bindgen = "0.2.89"

[serve]
address = "0.0.0.0"
